# Generated by Django 2.1.5 on 2018-01-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrients',
            name='food',
        ),
        migrations.AddField(
            model_name='nutrients',
            name='description',
            field=models.CharField(default='cat', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutrients',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
