# Generated by Django 2.1.7 on 2019-02-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20180101_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodToAvoid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=500)),
            ],
        ),
    ]
