# Generated by Django 2.1.7 on 2019-04-29 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20190223_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrients',
            name='agegroup',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutrients',
            name='recommended',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
