# Generated by Django 2.1.7 on 2019-04-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_auto_20190429_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrients',
            name='agegroup',
            field=models.CharField(choices=[('ONE', 'ONE'), ('TWO', 'TWO'), ('THREE', 'THREE')], default='ONE', max_length=255),
        ),
    ]
