version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pillow
    versions:
    - 8.1.0
    - 8.1.1
    - 8.1.2
  - dependency-name: django-crispy-forms
    versions:
    - 1.10.0
    - 1.11.0
    - 1.11.1
  - dependency-name: autopep8
    versions:
    - 1.5.4
    - 1.5.5
  - dependency-name: djangorestframework
    versions:
    - 3.12.2
  - dependency-name: django
    versions:
    - 2.2.13
  - dependency-name: gunicorn
    versions:
    - 20.0.4
